import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="card-body">
        <h1  className="card-title">
          Welcome to Material Center
        </h1>
        <h6 className="card-subtitle mb-2 text-muted">
          <Link href="/users/user">Do not click</Link>
        </h6>
      </div>
    </div>
  )
}

export default Home;
