import React from 'react';
import Head from 'next/head';
import styles from 'styles/Home.module.css';
import MaterialCard from 'components/MaterialCard';

const Home = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Material Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.cards}>
        <h1 className={styles.question}>
          You have gained a level. Choose a stat to increase.
        </h1>
        <MaterialCard material='Attack' />
        <MaterialCard material='Defense' />
        <MaterialCard material='Mana' />
        <MaterialCard material='Speed' />
      </div>
    </div>
  );
};

export default Home;
